vinayaksakhare/sales

- angular-src/src/app/components/upload/upload.component.ts
- config/client.config.js
- helpers/client.helper.js
- models/client.js
- routes/clients.js
1. "uploadBy" field is added while saving xls data to db.
2. "clients/data/" API is added to get all client data
3. client code is refactored
> added uploader details and code refactored

- angular-src/src/app/components/upload/upload.component.html
- routes/clients.js
1.  Added API to fetch data by uploaded name :  /clients/data/vinayak
2.  Updated UI for upload page
> fetch data by uploader name

- angular-src/src/app/components/upload/upload.component.html
- angular-src/src/app/services/dashboard.service.ts
- package.json
- routes/clients.js
1. Redis cache added for URI "clients/cachedata/vinayak"
2. file upload extensions added
> redis caching added

- helpers/client.helper.js
- helpers/redis.helper.js
- routes/clients.js
Added 2 APIs :
1. multi-update for assignedTo
2. client update
> added assignedTo multi-update and client update API

- angular-src/src/app/services/dashboard.service.ts
- routes/clients.js
Added following APIs for clients :
1. /data
2. /task/:id
3. /task
4. /assignto/:assignto
5. /assignto
> added new api for clients

- routes/clients.js
Updated cache after task is assigned to user
> cache updated after assignto

- helpers/redis.helper.js
- routes/clients.js
Client data is updated in cache after edit
> updated cache after edit client

- routes/clients.js
updated client cache after uploading new data via xls upload functionality
> updated client cache after uploading new data

- README.md
updated readme file for redis commands
> updated readme file for redis

- models/client.js
- routes/clients.js
updated Client API for reminder date. Client schema is updated to add created, updated date
> updated client api for reminder date

- app.js
- models/client.js
- models/comment.js
- routes/comments.js
Comment module API added :
1. Add Comment : 'comments/add'
2. Get Comments by client : 'comments/data/:clientId
3. Update Comment : 'comments/update'
> Comment module

- models/client.js
- models/comment.js
- routes/clients.js
1. Get Reminder by assignee and date-range : /reminders/:assignedto/:startdate/:enddate
2. Updated client & comment schema
> reminder date API added and updated client & comment schema

- angular-src/src/app/components/mytasks/mytasks.component.html
- angular-src/src/app/components/mytasks/mytasks.component.ts
- angular-src/src/app/services/my-tasks.service.ts
Parent Child communication for popup completed.
> mytask popup completed

- angular-src/src/app/components/popup/popup.component.html
- models/client.js
- routes/clients.js
Updated reminder date and text save/update functionality
> reminder date functionality updated

- models/client.js
> console added

- models/client.js
- models/comment.js
- routes/clients.js
Updated client API to send reminder by ascending datetime
> added sort by reminder datetime

- models/user.js
- routes/users.js
Added role in user module and updated respective methods
> added role in user module

- angular-src/src/app/components/profile/profile.component.html
- angular-src/src/app/components/register/register.component.html
- angular-src/src/app/components/register/register.component.ts
- angular-src/src/app/services/validate.service.ts
> roles feature added

- models/comment.js
updated comment schema for bdm. Now sending bdm as an object
> updated comment schema for bdm

- models/user.js
- routes/users.js
Edit Profile API added  : 
URI : "/users/profile" 
method : POST
> update profile API added

- angular-src/src/app/components/upload/upload.component.ts
- angular-src/src/app/services/client.service.ts
- app.js
- helpers/client.helper.js
- models/client.js
- models/comment.js
- routes/clients.js
- routes/comments.js
Client API code cleanup
Renamed API according to new standards
> client APIs restructured

- app.js
- models/teamdata.js
- routes/teamdata.js
Teamdata API added.
URI : localhost:3000/teamdata/callToMeeting
Method: POST
Data : {
"bdm" : ["ravi@etouch.net", "ashish@etouch.net"],
"fromDate": "Thu Apr 27 2017 00:00:00 GMT-0700 (Pacific Daylight Time)",
"toDate": "Sun May 28 2017 23:59:59 GMT-0700 (Pacific Daylight Time)"
}
> callToMeeting API call added

- angular-src/src/app/app.module.ts
- angular-src/src/app/components/edit-profile/edit-profile.component.html
- angular-src/src/app/components/edit-profile/edit-profile.component.spec.ts
- angular-src/src/app/components/edit-profile/edit-profile.component.ts
- angular-src/src/app/components/profile/profile.component.html
- angular-src/src/app/components/profile/profile.component.ts
- angular-src/src/app/services/client.service.ts
profile edit update feature completed
> edit Profile feature completed

- models/user.js
- routes/users.js
Added caching for BDMs and all users API
> caching added for bdm and users

- models/teamdata.js
- routes/teamdata.js
API for top 5 callers of the month : 
Method : GET
http://localhost:3000/teamdata/topusers
> API added for top 5 users

- models/comment.js
- models/teamdata.js
- routes/teamdata.js
1. API for last 4 months meetings :
Method : GET
http://localhost:3000/teamdata/meetingsscheduled
2. Changed type of ClientId in comments schema to ObjectId
> API added for meetings-scheduled

- docs/ServerAPI.md
- models/client.js
- routes/clients.js
API added for updating BDMs for multiple records :
URI : http://localhost:3000/clients/bdm
Method : POST
data:  {
"bdm" : {
"name" : "testbdm1",
"email" : "testbdm1@etouch.net"
},
"ids": ["5910b79fbc82a033cc2bfbb4",
"5910b79fbc82a033cc2bfc27"]
}
> multi client BDM update

- .gitignore
- angular-src/src/app/services/dashboard.service.ts
- docs/ServerAPI.md
- helpers/client.helper.js
- routes/clients.js
1. Updated clients data API
2. Updated gitignore file for .vscode
3. Updated server API file
> Updated API for Role wise clients data

- angular-src/src/app/components/calls-meeting-report/calls-meeting-report.component.ts
- angular-src/src/app/components/edit-profile/edit-profile.component.ts
- angular-src/src/app/components/login/login.component.ts
- angular-src/src/app/services/client.service.ts
- angular-src/src/app/services/user.service.ts
- models/user.js
- routes/users.js
Updated local storage user data after profile update.
cleanup code
> updated local storage after user update

- docs/ServerAPI.md
- routes/clients.js
API added for new client
Server file updated
> API for new client added

- helpers/redis.helper.js
- routes/users.js
Keys 'all_users' & 'bdm_users' deleted after profile update
> cache updated after profile update

- angular-src/src/app/components/bdm-filter/bdm-filter.component.ts
- angular-src/src/app/components/comment/comment.component.ts
- angular-src/src/app/components/login/login.component.ts
- angular-src/src/app/components/meetings-scheduled/meetings-scheduled.component.ts
- angular-src/src/app/components/my-grid-application/my-grid-application.component.ts
- angular-src/src/app/components/notification/notification.component.ts
- angular-src/src/app/components/notification/notification.service.ts
- angular-src/src/app/components/profile/profile.component.ts
- angular-src/src/app/components/register/register.component.ts
- angular-src/src/app/components/reminders/reminders.component.ts
- angular-src/src/app/components/shared-components/user-calls-line-chart/user-calls-line-chart.component.ts
- angular-src/src/app/components/top-callers/top-callers.component.ts
- angular-src/src/app/services/my-tasks.service.ts
- angular-src/src/styles.css
1. Fixed flash messages z-index
2. Removed console logs
> flash message z-index fix and removed console logs

- angular-src/src/app/components/my-grid-application/my-grid-application.component.html
- angular-src/src/app/components/navbar/navbar.component.html
- angular-src/src/app/components/new-client/new-client.component.css
- angular-src/src/app/components/new-client/new-client.component.html
User Interface Changes for Client Features
> User Interface Changes for Client

- angular-src/src/app/components/navbar/navbar.component.html
- angular-src/src/app/components/profile/profile.component.html
> new profile changes

- routes/users.js
updated user and bdm cache after new user added to system
> updated cache after new user created

- package.json
> updated author name in package.json

- models/client.js
If salutation is not provided default salutation is set to empty string
> default salutation added

- routes/clients.js
First name and last name are mandatory fields for client. If those are not present data wont be uploaded.
> restricted empty client upload

- routes/clients.js
added linkedin url in update flow
> added linkedin url in update flow

- angular-src/src/app/components/my-grid-application/my-grid-application.component.html
- angular-src/src/app/components/popup/popup.component.html
> linkedin URL added and able to modigy

- app.js
- docs/ServerAPI.md
- models/userdata.js
- routes/userdata.js
Added API for User chart data which returns daily/ weekly call records based on selection
> Userchart api

- angular-src/src/app/components/my-grid-application/my-grid-application.component.html
- angular-src/src/app/components/my-grid-application/my-grid-application.component.ts
- angular-src/src/app/services/dashboard.service.ts
- docs/ServerAPI.md
- models/client.js
- routes/clients.js
Delete multiple client flow added
> delete client flow added

- docs/ServerAPI.md
- models/userdata.js
- routes/userdata.js
API added to retrieve clientwise user data
> clientwise userdata API is added

- config/client.config.js
- models/client.js
added switchboard option in client model
> client model updated for switchboard

- README.md
- changeLog.md
- package.json
Added release notes for version 1.1.0
> release notes added

- docs/DbScripts.md
db script updated for new statuses
> db script updated

- angular-src/src/app/components/comment/comment-item/comment-item.component.css
- angular-src/src/app/components/comment/comment-item/comment-item.component.html
- angular-src/src/app/components/comment/comment-item/comment-item.component.ts
- angular-src/src/app/services/client.service.ts
Edit comment: User can edit comment text and type.
> Amey edit comment

- app.js
Removed deprecation warning coming for mongo client.
> removed deprecation warning for mongoose

- app.js
Reverted changes for mongoose error
> mongoose-error-reverted
